"""
CodeExecutor skill — runs Python code in a sandboxed subprocess.

Allows the agent to execute code snippets (e.g. generated by CodeWriter)
and observe stdout/stderr.  Execution is time-limited and confined to a
temporary sandbox directory.

ReAct usage::

    Thought: Let me test the Fibonacci function.
    Action[code_executor]:
    ```python
    def fibonacci(n):
        if n <= 1:
            return n
        return fibonacci(n - 1) + fibonacci(n - 2)

    print(fibonacci(10))
    ```
    Observation: STDOUT: 55

Security measures:
    - Hard timeout (default 10 s) via ``subprocess.run(timeout=...)``.
    - Code runs in an isolated sandbox directory.
    - Temporary script file is deleted after execution.
    - stderr is captured and reported separately.
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from skills.registry import BaseSkill

logger = logging.getLogger(__name__)


def _extract_python_code(text: str) -> str:
    """Extract Python source from a fenced code block, or return raw text.

    Handles ``````python ... `````` and ````` ... ````` wrappers.
    If no fenced block is found, the entire text is treated as code.
    """
    # Try ```python ... ```
    match = re.search(r"```python\s*\n(.*?)```", text, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Try generic ``` ... ```
    match = re.search(r"```\s*\n(.*?)```", text, re.DOTALL)
    if match:
        return match.group(1).strip()

    # No fencing — treat entire input as code
    return text.strip()


class CodeExecutor(BaseSkill):
    """Executes Python code in a sandboxed subprocess.

    The agent provides a Python code snippet (optionally wrapped in a
    fenced code block).  The skill writes it to a temporary file,
    runs it with a timeout, captures output, and cleans up.

    Args:
        sandbox_dir: Directory where temporary scripts are created.
            Created automatically if it doesn't exist.
        timeout: Maximum execution time in seconds.
    """

    def __init__(
        self,
        sandbox_dir: str = "/tmp/agent_sandbox",
        timeout: int = 10,
    ) -> None:
        self._sandbox_dir = Path(sandbox_dir)
        self._timeout = timeout

    @property
    def name(self) -> str:
        return "code_executor"

    @property
    def description(self) -> str:
        return (
            "Execute a Python code snippet and return its output. "
            "Input: Python code (optionally wrapped in ```python``` fences). "
            "Output: STDOUT and STDERR from execution. "
            "Timeout: {timeout}s. Use for testing, verification, or computation."
        ).format(timeout=self._timeout)

    def execute(self, input_text: str) -> str:
        """Run the provided Python code and return captured output.

        Args:
            input_text: Python source code, optionally in a fenced block.

        Returns:
            A formatted string with STDOUT and STDERR sections,
            or an error/timeout message.
        """
        code = _extract_python_code(input_text)
        if not code:
            return "Error: no code provided."

        # Ensure sandbox directory exists
        self._sandbox_dir.mkdir(parents=True, exist_ok=True)

        # Write to a temporary file
        script_path: Optional[str] = None
        try:
            fd, script_path = tempfile.mkstemp(
                suffix=".py",
                prefix="agent_exec_",
                dir=str(self._sandbox_dir),
            )
            with os.fdopen(fd, "w") as f:
                f.write(code)

            logger.info(
                "CodeExecutor: running %s (%d chars, timeout=%ds)",
                script_path, len(code), self._timeout,
            )

            # Execute in subprocess
            result = subprocess.run(
                ["python3", script_path],
                capture_output=True,
                text=True,
                timeout=self._timeout,
                cwd=str(self._sandbox_dir),
            )

            return self._format_result(result)

        except subprocess.TimeoutExpired:
            logger.warning("CodeExecutor: script timed out after %ds", self._timeout)
            return (
                f"Error: execution timed out after {self._timeout} seconds.\n"
                "Hint: simplify the code or increase the timeout."
            )
        except FileNotFoundError:
            return "Error: python3 interpreter not found."
        except Exception as exc:
            logger.error("CodeExecutor: unexpected error: %s", exc)
            return f"Error: {exc}"
        finally:
            # Clean up temporary file
            if script_path and os.path.exists(script_path):
                try:
                    os.unlink(script_path)
                except OSError:
                    pass

    @staticmethod
    def _format_result(result: subprocess.CompletedProcess) -> str:
        """Format subprocess output for ReAct observation.

        Args:
            result: Completed subprocess result.

        Returns:
            Formatted STDOUT/STDERR string.
        """
        parts: list[str] = []

        stdout = result.stdout.strip() if result.stdout else ""
        stderr = result.stderr.strip() if result.stderr else ""

        if stdout:
            parts.append(f"STDOUT:\n{stdout}")

        if stderr:
            parts.append(f"STDERR:\n{stderr}")

        if result.returncode != 0:
            parts.append(f"(exit code: {result.returncode})")

        if not parts:
            parts.append("(no output)")

        return "\n\n".join(parts)

    def __repr__(self) -> str:
        return (
            f"CodeExecutor(sandbox={str(self._sandbox_dir)!r}, "
            f"timeout={self._timeout}s)"
        )
